---
title: "Calculator markdown"
author: "Adrian Jimenez"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**1. Load required packages**
```{r ui, echo=TRUE, results='hide', message=FALSE, warning=FALSE}
library(shiny)
library(caret)
library(base64)
library(rsconnect)
library(readxl)
library(pROC)
library(gbm)
require(MASS)
library(ResourceSelection)
```


**2. Define user interface for application**
```{r define_ui, error=TRUE}
ui <- fluidPage(
  
  #2.1 Application title
  titlePanel("Risk Calculator for 12-Month Survival Following Glioblastoma Surgery"),
  
  #2.2 Sidebar with numeric and slider input
  sidebarLayout(
    sidebarPanel(
      numericInput(inputId = "age",
                   label = "Enter Patient Age",
                   min = 0,
                   max = 10000,
                   value = 50),
      numericInput(inputId = "caseload",
                   label = "Enter Caseload",
                   min = 0,
                   max = 10000,
                   value=100),
      selectInput(inputId = "chemotherapy",
                  label = "Select Patient Chemotherapy Status",
                  choices=
                    list(
                      "Received Chemotherapy"=1,
                      "Did Not Receive Chemotherapy"=0),
                  selected=1),
      selectInput(inputId = "comorbidity",
                  label = "Select Patient Comorbidity Status",
                  choices=
                    list(
                      "Yes"=1,
                      "No"=0),
                  selected=0),
      helpText("Comorbidity Status: Presence of any systemic comorbidity such as 
               diabetes, coronary heart disease, chronic obstructive pulmonary disease, etc."),
      selectInput(inputId = "idh",
                  label = "Select IDH Status",
                  choices=
                    list(
                      "Mutated"=1,
                      "Wild-type"=0),
                  selected=1),
      numericInput(inputId = "kps",
                   label = "Enter KPS Score",
                   min = 1,
                   max = 100,
                   value = 100),
    selectInput(inputId = "sex",
                label = "Select Patient Sex",
                choices=
                  list(
                    "Male"=1,
                    "Female"=0),
                selected=1),
    selectInput(inputId = "mgmt",
                label = "Select MGMT Methylation Status",
                choices=
                  list(
                    "Methylated"=1,
                    "Not Methylated"=0),
                selected=1),
    selectInput(inputId = "midline",
                label = "Does Tumor Extend Into The Midline?",
                choices=
                  list(
                    "Yes"=1,
                    "No"=0),
                selected=0),
    selectInput(inputId = "prior_surgery",
                label = "Has The Patient Had Prior Surgery?",
                choices=
                  list(
                    "Yes"=1,
                    "No"=0),
                selected=0),
    numericInput(inputId = "radiotherapy_dose",
                 label = "Enter Radiotherapy Dose (in Gray)",
                 min = 1,
                 max = 10000,
                 value = 20),
    numericInput(inputId = "size",
                 label = "Enter Maximum Tumor Diameter (in cm)",
                 min = 1,
                 max = 10000,
                 value = 3),
    selectInput(inputId = "tert",
                label = "Select TERT Promoter Mutation Status",
                choices=
                  list(
                    "Mutated"=1,
                    "Not Mutated"=0),
                selected=1)),
    #2.3 Output probability of 12-Month Survival
    mainPanel(
      tabsetPanel(type="tabs",
                  tabPanel("Disclaimer",'The following calculator was developed using a simulated dataset and should only be 
                           used for educational purposes to supplement the following publication:"Deployment of Clinical 
                           Prediction Models: Nomograms and Online Calculators". Under no circumstances should this 
                           calculator be used to provide medical advice.'),
                  tabPanel("Calculator Output",tableOutput("model_table")))
    )
  )
)

```

**3. Define server logic required to output probability**
```{r logic, error=TRUE,warning=FALSE,message=FALSE}
server <- function(input, output) {
  
  #3.1 Load GBM model file
  gbmfit <- readRDS("gbmfit")
  
  #3.2 Define reactive output
  model_output <- reactive({
    
    #3.2.1 Specify type of output and formula for generating output
    data.frame(
      `Result` = c("Probability (%) of Survival Within 12 Months of Surgery"),
      `Output` = c(predict.train(gbmfit,data.frame(Age=as.numeric(input$age), 
                                                   Caseload=as.numeric(input$caseload), 
                                                   Chemotherapy=as.factor(input$chemotherapy), 
                                                   Comorbidity=as.factor(input$comorbidity), 
                                                   IDH=as.factor(input$idh), 
                                                   KPS=as.numeric(input$kps), 
                                                   Male=as.factor(input$sex), 
                                                   MGMT=as.factor(input$mgmt), 
                                                   Midline=as.factor(input$midline), 
                                                   PriorSurgery=as.factor(input$prior_surgery), 
                                                   RadiotherapyDose=as.numeric(input$radiotherapy_dose), 
                                                   Size=as.numeric(input$size),TERTp=as.factor(input$tert)),
                                 type="prob")[,"yes"]*100))
    
  })
  
  #3.3 Display output
  output$model_table <- renderTable(model_output())
}
```

**4. Run the application**
```{r run,error=TRUE,warning=FALSE,message=FALSE,results='hide'}
shinyApp(ui = ui, server = server)
```