---
title: "Nomogram markdown"
author: "Adrian Jimenez"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r data, include=FALSE}
#used to independently load a dataset if the MICN "script_classification" has not been used to load the training data into the global environment
train <- readRDS("train dataset")
```

**1. Obtain distribution summaries for variables within "train" dataset**
```{r cars,results='hide',message=FALSE,warning=FALSE}
library(rms)

train_dist <- datadist(train)
options(datadist='train_dist')
```

**2. Define logistic regression model**
```{r logit}
lrfit_rms <- lrm(TwelveMonths ~.,data=train)
```

**3. Construct and format nomogram **
```{r nomogram}
nom.lrfit_rms <- nomogram(lrfit_rms,fun=function(x)1/(1+exp(-x)),
                          lp=FALSE,
                          funlabel="Predicted Probability of 12-Month Postoperative Survival",
                          fun.at = c(0.01,0.25,0.95,0.99))
```

**4. Plot nomogram**
```{r plot_nomogram, echo=TRUE, fig.show="hide"}
plot(nom.lrfit_rms)
```
